AWSTemplateFormatVersion: "2010-09-09"
Description: "cafe S3 template"
Resources:
  S3BQ1P6:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      MetricsConfigurations:
        - Id: EntireBucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - S3BQ1P6
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - S3BQ1P6
          - DomainName
    Description: Name of S3 bucket to hold website content
